# Generated by Django 3.1.2 on 2020-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of product', max_length=100)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price of Product')),
                ('manufacturer', models.CharField(default='', help_text='Name of manufacturer', max_length=100)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('payment_option', models.CharField(default='Cash On Delivery (C.O.D.)', max_length=50)),
            ],
        ),
    ]
