# Generated by Django 3.1.2 on 2020-10-08 14:36

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.product')),
                ('description', models.TextField(default='', help_text='Description of the product')),
                ('country_of_origin', models.CharField(default=None, max_length=20)),
                ('photos_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=450), blank=True, default=None, size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=20), blank=True, default=None, size=None)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coupons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=20), blank=True, default=None, size=None)),
            ],
        ),
    ]
