# Generated by Django 3.1.2 on 2020-10-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
