# Generated by Django 3.1.3 on 2020-11-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantities',
            new_name='products',
        ),
    ]
