# Generated by Django 3.1.3 on 2020-11-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201126_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantities',
            new_name='products',
        ),
    ]
