# Generated by Django 3.1.3 on 2020-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201126_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityproduct',
            old_name='product',
            new_name='productId',
        ),
    ]
