# Generated by Django 3.1.2 on 2020-10-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201008_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='isInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='payment_option',
            new_name='paymentOption',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_link',
            new_name='thumbnails',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='country_of_origin',
            new_name='countryOfOrigin',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='photos_links',
            new_name='photos',
        ),
    ]
