# Generated by Django 3.1.2 on 2020-10-14 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201010_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('userId', models.UUIDField(default=uuid.UUID('16db8f91-9049-4d4a-b0a2-e688504e0df5'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=320)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.UUIDField(default=uuid.UUID('59c51589-81d7-4aac-8bde-7325de3f15b9'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=1)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pinCode', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.details')),
            ],
        ),
    ]
