# Generated by Django 3.1.3 on 2020-12-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201129_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSlug',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
