# Generated by Django 3.1.2 on 2020-10-14 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20201014_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('6e58f5e9-cab9-45ef-a36e-51dd8f4f88c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
