# Generated by Django 3.1.2 on 2020-10-14 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20201014_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('9484afeb-5e62-4d94-ae42-0ac411f8141a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
