# Generated by Django 3.1.3 on 2020-12-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20201229_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
