# Generated by Django 3.1.2 on 2020-10-14 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20201014_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
