# Generated by Django 3.1.2 on 2021-01-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20201230_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='brand',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
