# Generated by Django 3.1.2 on 2020-10-14 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20201014_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=1)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pinCode', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.details')),
            ],
        ),
    ]
